/* Generated by Yosys 0.61+44 (git sha1 57ac113b7, clang++ 18.1.8 -fPIC -O3) */

module example(a, b, y);
  input a;
  wire a;
  input b;
  wire b;
  output y;
  wire y;
  XOR2X3H7L b_XOR2X3H7L_A (
    .A(b),
    .B(a),
    .Y(y)
  );
endmodule
