/* Generated by Yosys 0.61+44 (git sha1 57ac113b7, clang++ 18.1.8 -fPIC -O3) */

module prioty8_3_encoder(in_0_, in_1_, in_2_, in_3_, in_4_, in_5_, in_6_, in_7_, en, out_0_, out_1_, out_2_, valid);
  input in_0_;
  wire in_0_;
  input in_1_;
  wire in_1_;
  input in_2_;
  wire in_2_;
  input in_3_;
  wire in_3_;
  input in_4_;
  wire in_4_;
  input in_5_;
  wire in_5_;
  input in_6_;
  wire in_6_;
  input in_7_;
  wire in_7_;
  input en;
  wire en;
  output out_0_;
  wire out_0_;
  output out_1_;
  wire out_1_;
  output out_2_;
  wire out_2_;
  output valid;
  wire valid;
  wire en_NAND2X0P5H7L_A_Y;
  wire en_NAND3BBX1P4H7L_C_Y;
  wire en_NAND3BX0P5H7L_C_Y;
  wire out_OAI211X1P4H7L_Y_A0;
  wire out_OAOI211X1P4H7L_Y_A0;
  wire out_OAOI211X1P4H7L_Y_B0;
  wire valid_AOI31X2H7L_Y_A0;
  wire valid_AOI31X2H7L_Y_A1;
  wire valid_AOI31X2H7L_Y_A2;
  wire valid_AOI31X2H7L_Y_B0;
  INVX1H7L en_INVX1H7L_A (
    .A(en),
    .Y(valid_AOI31X2H7L_Y_B0)
  );
  NAND2X0P5H7L en_NAND2X0P5H7L_A (
    .A(en),
    .B(in_7_),
    .Y(en_NAND2X0P5H7L_A_Y)
  );
  NAND3BBX1P4H7L en_NAND3BBX1P4H7L_C (
    .AN(in_6_),
    .BN(in_4_),
    .C(en),
    .Y(en_NAND3BBX1P4H7L_C_Y)
  );
  NAND3BX0P5H7L en_NAND3BX0P5H7L_C (
    .AN(in_6_),
    .B(in_5_),
    .C(en),
    .Y(en_NAND3BX0P5H7L_C_Y)
  );
  NOR2X0P5H7L out_NOR2X0P5H7L_Y (
    .A(valid_AOI31X2H7L_Y_B0),
    .B(valid_AOI31X2H7L_Y_A0),
    .Y(out_2_)
  );
  OAI211X1P4H7L out_OAI211X1P4H7L_Y (
    .A0(out_OAI211X1P4H7L_Y_A0),
    .A1(en_NAND3BBX1P4H7L_C_Y),
    .B0(en_NAND2X0P5H7L_A_Y),
    .C0(en_NAND3BX0P5H7L_C_Y),
    .Y(out_0_)
  );
  AOI2XB1X0P5H7L out_OAI211X1P4H7L_Y_A0_AOI2XB1X0P5H7L_Y (
    .A0(in_1_),
    .A1N(in_2_),
    .B0(in_3_),
    .Y(out_OAI211X1P4H7L_Y_A0)
  );
  OAOI211X1P4H7L out_OAOI211X1P4H7L_Y (
    .A0(out_OAOI211X1P4H7L_Y_A0),
    .A1(valid_AOI31X2H7L_Y_A1),
    .B0(out_OAOI211X1P4H7L_Y_B0),
    .C0(valid_AOI31X2H7L_Y_B0),
    .Y(out_1_)
  );
  OR2X0P5H7L out_OAOI211X1P4H7L_Y_A0_OR2X0P5H7L_Y (
    .A(in_5_),
    .B(in_4_),
    .Y(out_OAOI211X1P4H7L_Y_A0)
  );
  NOR2X0P5H7L out_OAOI211X1P4H7L_Y_B0_NOR2X0P5H7L_Y (
    .A(in_6_),
    .B(in_7_),
    .Y(out_OAOI211X1P4H7L_Y_B0)
  );
  AOI31X2H7L valid_AOI31X2H7L_Y (
    .A0(valid_AOI31X2H7L_Y_A0),
    .A1(valid_AOI31X2H7L_Y_A1),
    .A2(valid_AOI31X2H7L_Y_A2),
    .B0(valid_AOI31X2H7L_Y_B0),
    .Y(valid)
  );
  NOR4X2H7L valid_AOI31X2H7L_Y_A0_NOR4X2H7L_Y (
    .A(in_6_),
    .B(in_5_),
    .C(in_4_),
    .D(in_7_),
    .Y(valid_AOI31X2H7L_Y_A0)
  );
  NOR2X0P5H7L valid_AOI31X2H7L_Y_A1_NOR2X0P5H7L_Y (
    .A(in_2_),
    .B(in_3_),
    .Y(valid_AOI31X2H7L_Y_A1)
  );
  NOR2X0P5H7L valid_AOI31X2H7L_Y_A2_NOR2X0P5H7L_Y (
    .A(in_1_),
    .B(in_0_),
    .Y(valid_AOI31X2H7L_Y_A2)
  );
endmodule
