/* Generated by Yosys 0.61+44 (git sha1 57ac113b7, clang++ 18.1.8 -fPIC -O3) */

module sCPU(clk, rst, out_seg0_0_, out_seg0_1_, out_seg0_2_, out_seg0_3_, out_seg0_4_, out_seg0_5_, out_seg0_6_, out_seg0_7_, out_seg1_0_, out_seg1_1_, out_seg1_2_, out_seg1_3_, out_seg1_4_, out_seg1_5_, out_seg1_6_, out_seg1_7_);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output out_seg0_0_;
  wire out_seg0_0_;
  output out_seg0_1_;
  wire out_seg0_1_;
  output out_seg0_2_;
  wire out_seg0_2_;
  output out_seg0_3_;
  wire out_seg0_3_;
  output out_seg0_4_;
  wire out_seg0_4_;
  output out_seg0_5_;
  wire out_seg0_5_;
  output out_seg0_6_;
  wire out_seg0_6_;
  output out_seg0_7_;
  wire out_seg0_7_;
  output out_seg1_0_;
  wire out_seg1_0_;
  output out_seg1_1_;
  wire out_seg1_1_;
  output out_seg1_2_;
  wire out_seg1_2_;
  output out_seg1_3_;
  wire out_seg1_3_;
  output out_seg1_4_;
  wire out_seg1_4_;
  output out_seg1_5_;
  wire out_seg1_5_;
  output out_seg1_6_;
  wire out_seg1_6_;
  output out_seg1_7_;
  wire out_seg1_7_;
  TIEHIH7L out_seg0_TIEHIH7L_Z (
    .Z(out_seg0_1_)
  );
  TIELOH7L out_seg0_TIELOH7L_Z (
    .Z(out_seg0_0_)
  );
  assign out_seg0_5_ = out_seg0_0_;
  assign out_seg0_4_ = out_seg0_0_;
  assign out_seg0_3_ = out_seg0_0_;
  assign out_seg0_2_ = out_seg0_0_;
  assign out_seg1_7_ = out_seg0_0_;
  assign out_seg1_6_ = out_seg0_0_;
  assign out_seg1_5_ = out_seg0_0_;
  assign out_seg1_4_ = out_seg0_0_;
  assign out_seg1_3_ = out_seg0_0_;
  assign out_seg1_2_ = out_seg0_0_;
  assign out_seg1_1_ = out_seg0_1_;
  assign out_seg1_0_ = out_seg0_0_;
  assign out_seg0_7_ = out_seg0_0_;
  assign out_seg0_6_ = out_seg0_0_;
endmodule
